### ISSUE TITLE
cutecoin.tools.exceptions.NoPeerAvailable: Error : No peer answered in Ucoin 

### ISSUE THREAD

**Issue by Folatt** [ucoin-io/ucoin#124] opened 2015-06-26 05:39 UTC
```sh
Traceback (most recent call last):
  File "/home/gael/cutecoin/src/cutecoin/gui/mainwindow.py", line 184, in loader_finished
  File "/home/gael/cutecoin/src/cutecoin/gui/mainwindow.py", line 367, in refresh
  File "/home/gael/cutecoin/src/cutecoin/gui/mainwindow.py", line 299, in refresh_communities
  File "/home/gael/cutecoin/src/cutecoin/gui/currency_tab.py", line 84, in refresh
  File "/home/gael/cutecoin/src/cutecoin/gui/transactions_tab.py", line 38, in __init__
  File "/home/gael/cutecoin/src/cutecoin/gui/transactions_tab.py", line 42, in refresh
  File "/home/gael/cutecoin/src/cutecoin/core/community.py", line 348, in get_block
  File "/home/gael/cutecoin/src/cutecoin/core/community.py", line 397, in request
  File "/home/gael/cutecoin/src/cutecoin/core/community.py", line 89, in request
  File "/home/gael/cutecoin/src/cutecoin/core/community.py", line 421, in request
cutecoin.tools.exceptions.NoPeerAvailable: Error : No peer answered in Ucoin Florin - Alpha community (1 peers available)
```

My address is sluimers.net:61215.

**Comment by Insoleet** [comment] 2015-06-26 05:50
>
wget http://sluimers.net:61215/blockchain/Current
--2015-06-26 07:49:54--  http://sluimers.net:61215/blockchain/Current
Résolution de sluimers.net (sluimers.net)… 83.163.103.119
Connexion à sluimers.net (sluimers.net)|83.163.103.119|:61215… **failed : Connection refused**

Please check access to your node.

**Comment by Folatt** [comment] 2015-06-26 05:53
And how do I do that? I'm clueless.

**Comment by Folatt** [comment] 2015-06-26 06:02
More errors: 

```Traceback (most recent call last):
  File "/home/gael/cutecoin/src/cutecoin/gui/process_cfg_community.py", line 128, in next
  File "/home/gael/cutecoin/src/cutecoin/gui/process_cfg_community.py", line 60, in process_next
  File "/home/gael/cutecoin/src/cutecoin/core/community.py", line 130, in create
  File "/home/gael/cutecoin/src/cutecoin/core/net/network.py", line 51, in create
AttributeError: 'NoneType' object has no attribute 'currency'
Traceback (most recent call last):
  File "/home/gael/cutecoin/src/cutecoin/core/community.py", line 262, in monetary_mass
  File "/home/gael/cutecoin/src/cutecoin/core/community.py", line 397, in request
  File "/home/gael/cutecoin/src/cutecoin/core/community.py", line 89, in request
  File "/home/gael/cutecoin/src/cutecoin/core/community.py", line 403, in request
  File "/home/gael/cutecoin/lib/ucoinpy/api/bma/__init__.py", line 81, in get
  File "/home/gael/cutecoin/lib/ucoinpy/api/bma/blockchain/__init__.py", line 69, in __get__
  File "/home/gael/cutecoin/lib/ucoinpy/api/bma/__init__.py", line 116, in requests_get
ValueError: status code != 200 => 400 (Block not found)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gael/cutecoin/src/cutecoin/gui/mainwindow.py", line 184, in loader_finished
  File "/home/gael/cutecoin/src/cutecoin/gui/mainwindow.py", line 367, in refresh
  File "/home/gael/cutecoin/src/cutecoin/gui/mainwindow.py", line 298, in refresh_communities
  File "/home/gael/cutecoin/src/cutecoin/gui/currency_tab.py", line 56, in __init__
  File "/home/gael/cutecoin/src/cutecoin/gui/wallets_tab.py", line 40, in __init__
  File "/home/gael/cutecoin/src/cutecoin/gui/wallets_tab.py", line 103, in refresh
  File "/home/gael/cutecoin/src/cutecoin/core/community.py", line 265, in monetary_mass
TypeError: argument of type 'ValueError' is not iterable
QVariantMap DBusMenuExporterDBus::getProperties(int, const QStringList&) const: Condition failed: action```

**Comment by Folatt** [comment] 2015-06-26 06:04
And stuff on my server side:

```Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
[2015-06-26 05:59:16.567] [WARN] ucoin_default - Local node is not a member. Waiting to be a member before computing a block.
[2015-06-26 06:00:16.575] [WARN] ucoin_default - Local node is not a member. Waiting to be a member before computing a block.
[2015-06-26 06:01:16.579] [WARN] ucoin_default - Local node is not a member. Waiting to be a member before computing a block.
[2015-06-26 06:02:16.583] [WARN] ucoin_default - Local node is not a member. Waiting to be a member before computing a block.```

**Comment by Insoleet** [comment] 2015-06-26 06:43
When I try to add your community I get this : 

>
DEBUG:community:Error : <class 'ucoinpy.api.bma.wot.Lookup'> : HTTPConnectionPool(host='192.168.178.30', port=61215): Max retries exceeded with url: /wot/lookup/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f91ac141b00>, 'Connection to 192.168.178.30 timed out. (connect timeout=15)'))

This is because of your peering document : 
http://sluimers.net:61215/network/Peering

```json
{

    "version": 1,
    "currency": "Ucoin Florin - Alpha",
    "endpoints": 

    [
        "BASIC_MERKLED_API 192.168.178.30 61215"
    ],
    "status": "UP",
    "block": "0-DA39A3EE5E6B4B0D3255BFEF95601890AFD80709",
    "signature": "2HrXxvAzUqE6Qx0J8ULD9vxc3f7BflaqpEB/fz0a9TBI+Uv7pP8dBifdqoS+D6ZECjXXQMIbDZxEVXl0y2/0AQ==",
    "raw": "Version: 1\nType: Peer\nCurrency: Ucoin Florin - Alpha\nPublicKey: EuwzpTks2taaAktTY1aEz6LBmzotABFYKPAE9E8EY7Sz\nBlock: 0-DA39A3EE5E6B4B0D3255BFEF95601890AFD80709\nEndpoints:\nBASIC_MERKLED_API 192.168.178.30 61215\n",
    "pubkey": "EuwzpTks2taaAktTY1aEz6LBmzotABFYKPAE9E8EY7Sz"

}
```

It declares an IP that we cannot join from the outside. It should declare your node public IP and the DNS used to join the node, "sluimers.net".

**Comment by Folatt** [comment] 2015-06-26 06:44
Just a sec, I'm rebooting because of another error I'm dealing with.

**Comment by c-geek** [comment] 2015-06-26 20:24
@Folatt you have to use public IPv4 address since you use a VPS server. `192.168.x.x` is private network.

The fact you give a DNS name is an help for us for remote contact, but since you choose a private IPv4, your node is listening to private network only.

@Insoleet OK

**Comment by c-geek** [comment] 2015-06-27 13:40
Duplicate of #89.

**Closed by c-geek** 2015-06-27 13:40 UTC
Labels: bug

**Comment by JMRedford** [comment] 2015-08-13 04:07
Is there a way to set this up on heroku or something?  I'm just trying to connect via a home router via an isp an am unfamiliar with setting up a static ip.

**Comment by Insoleet** [comment] 2015-08-13 06:02
You must set the proxy in the Python environment before launching Cutecoin. Its an environment variable to define.

**Comment by c-geek** [comment] 2015-08-14 10:28
@JMRedford I've added a new issue for this (#148)

If you would like to dive into the code, I would suggest you look at unit/integration tests.

First, two examples of a complete launching of ucoin instances, operations on them, and assertions about expected results:

* https://github.com/ucoin-io/ucoin/blob/master/test/integration/branches.js
* https://github.com/ucoin-io/ucoin/blob/master/test/integration/branches2.js

Also, you can explore the [Protocol rules](https://github.com/ucoin-io/ucoin/blob/master/test/integration/branches.js) through [test/fast/block/](https://github.com/ucoin-io/ucoin/tree/master/test/fast/block) folder, which contains 3 files testing respectively: format, local and global rules of incoming data.

Finally, you can study [bin/ucoind](https://github.com/ucoin-io/ucoin/blob/master/bin/ucoind) which is the entry point to launch ucoin software.

Please always keep a critical mind while looking at ucoin code since it is still under development phase.

Feel free to make any suggestion about code/tools improvements. I know we still have many things that can be enhanced!
