### ISSUE TITLE
Sync issue with MedianTime

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#288] opened 2015-12-29 15:54 UTC
There is an issue on block 42999 about MedianTime which blocks sync:
```bash
$ ucoind sync scith.ovh 8999
Progress:

Download: [||||||||||||||||||  ] 92 %
Apply:    [||||||||||||||||||  ] 91 %

Status: Wrong MedianTime
All done.
undefined
```
I also get it when syncthing with inso node:
```bash
[2015-12-29 14:15:45.659] [INFO] sync - Applying blocks #42000 to #42499...
[2015-12-29 14:15:46.589] [INFO] sync - Remaining a few seconds
[2015-12-29 14:15:47.930] [INFO] sync - Remaining a few seconds
[2015-12-29 14:15:48.933] [INFO] sync - Remaining a few seconds
[2015-12-29 14:15:50.259] [INFO] sync - Remaining a few seconds
[2015-12-29 14:15:50.889] [INFO] sync - Applying blocks #42500 to #42999...
[2015-12-29 14:15:51.349] [INFO] sync - Remaining a few seconds
[2015-12-29 14:15:52.737] [INFO] sync - Remaining a few seconds
[2015-12-29 14:15:53.844] [INFO] sync - Remaining a few seconds
[2015-12-29 14:15:53.921] [INFO] sync - 400 - Bad request.
{}
undefined
```

**Comment by M5oul** [comment] 2015-12-29 19:19
In fact, sync does not go to the end:
```bash
[2015-12-29 14:15:42.187] [INFO] sync - Applying blocks #41500 to #41999...
[2015-12-29 14:15:43.288] [INFO] sync - Remaining a few seconds
[2015-12-29 14:15:44.305] [INFO] sync - Remaining a few seconds
[2015-12-29 14:15:45.588] [INFO] sync - Remaining a few seconds
[2015-12-29 14:15:45.659] [INFO] sync - Applying blocks #42000 to #42499...
[2015-12-29 14:15:46.589] [INFO] sync - Remaining a few seconds
[2015-12-29 14:15:47.930] [INFO] sync - Remaining a few seconds
[2015-12-29 14:15:48.933] [INFO] sync - Remaining a few seconds
[2015-12-29 14:15:50.259] [INFO] sync - Remaining a few seconds
[2015-12-29 14:15:50.889] [INFO] sync - Applying blocks #42500 to #42999...
[2015-12-29 14:15:51.349] [INFO] sync - Remaining a few seconds
[2015-12-29 14:15:52.737] [INFO] sync - Remaining a few seconds
[2015-12-29 14:15:53.844] [INFO] sync - Remaining a few seconds
[2015-12-29 14:15:53.921] [INFO] sync - 400 - Bad request.
```

**Comment by c-geek** [comment] 2015-12-29 20:22
You have to `reset data` before doing sync, otherwise it tests rules which might lead to such issues for MetaB.

**Comment by M5oul** [comment] 2015-12-29 20:27
Yep, I `reset data`.

**Comment by c-geek** [comment] 2015-12-29 22:37
What if you try with my node (metab.ucoin.io:9201) ?

**Comment by M5oul** [comment] 2015-12-30 08:15
It works fine with my local node. I will try with the YunoHost package on a digitalocean.

**Comment by M5oul** [comment] 2015-12-30 16:12
Blocks doesn't exist on some nodes: http://metab.ucoin.fr:9201/blockchain/block/45900
Exist on this node: https://moul.re/ucoin/blockchain/block/45900

**Comment by Insoleet** [comment] 2016-01-03 22:16
Could be linked to the following logs on my node : 

```
ucoin_default-0 (err):                                                                     ^
ucoin_default-0 (err): TypeError: Cannot read property 'medianTime' of null
ucoin_default-0 (err):     at /home/ucoin/.ucoin/app/lib/globalValidator.js:249:93
ucoin_default-0 (err):     at fn (/home/ucoin/.ucoin/node_modules/async/lib/async.js:579:34)
ucoin_default-0 (err):     at Immediate._onImmediate (/home/ucoin/.ucoin/node_modules/async/lib/async.js:495:34)
ucoin_default-0 (err):     at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by c-geek** [comment] 2016-01-06 15:20
Duplicate of #282.

**Closed by c-geek** 2016-01-06 15:20 UTC
Labels: bug
